// Standalone gflags definitions for macOS (ROCKSDB_ONLY) builds.
// On Linux these come from backend/leanstore/Config.cpp via libleanstore.a.
// We only define the flags actually used by the RocksDB frontend path.

#include "gflags/gflags.h"

// --- Flags used by RocksDB.hpp, Logger, and experiment infrastructure ---
DEFINE_double(dram_gib, 1, "");
DEFINE_double(ssd_gib, 1700, "");
DEFINE_string(ssd_path, "./leanstore", "Position of SSD, gets persisted");
DEFINE_string(csv_path, "./log", "");
DEFINE_bool(csv_truncate, false, "");
DEFINE_bool(trunc, false, "Truncate file");
DEFINE_uint32(worker_threads, 4, "");
DEFINE_uint32(pp_threads, 1, "number of page provider threads");
DEFINE_bool(cpu_counters, true, "");
DEFINE_bool(pin_threads, false, "");
DEFINE_bool(smt, true, "");
DEFINE_bool(persist, false, "");
DEFINE_bool(recover, false, "");
DEFINE_string(persist_file, "./leanstore.json", "");
DEFINE_string(recover_file, "./leanstore.json", "");
// log_progress is defined in executable_helper.hpp
DEFINE_string(isolation_level, "si", "");
DEFINE_bool(optimistic_scan, true, "");
DEFINE_bool(mv, true, "");
DEFINE_bool(vi, true, "");
DEFINE_bool(print_debug, true, "");
DEFINE_bool(print_tx_console, true, "");
DEFINE_uint32(print_debug_interval_s, 1, "");
DEFINE_bool(profiling, false, "");
DEFINE_bool(profile_latency, false, "");
DEFINE_bool(measure_time, false, "");
DEFINE_bool(crc_check, false, "");
DEFINE_uint32(free_pct, 1, "");
DEFINE_uint32(partition_bits, 6, "");
DEFINE_uint32(write_buffer_size, 1024, "");
DEFINE_uint32(falloc, 0, "");
DEFINE_bool(worker_page_eviction, false, "");
DEFINE_bool(root, false, "");
DEFINE_string(tag, "", "");
DEFINE_string(zipf_path, "/bulk/zipf", "");
DEFINE_double(zipf_factor, 0.0, "");
DEFINE_double(target_gib, 0.0, "");
DEFINE_uint64(run_for_seconds, 10, "");
DEFINE_uint64(warmup_for_seconds, 10, "");
DEFINE_bool(contention_split, true, "");
DEFINE_uint64(cm_update_on, 7, "");
DEFINE_uint64(cm_period, 14, "");
DEFINE_uint64(cm_slowpath_threshold, 1, "");
DEFINE_bool(xmerge, false, "");
DEFINE_uint64(xmerge_k, 5, "");
DEFINE_double(xmerge_target_pct, 80, "");
DEFINE_double(tmp1, 0.0, "");
DEFINE_double(tmp2, 0.0, "");
DEFINE_double(tmp3, 0.0, "");
DEFINE_double(tmp4, 0.0, "");
DEFINE_double(tmp5, 0.0, "");
DEFINE_double(tmp6, 0.0, "");
DEFINE_double(tmp7, 0.0, "");
DEFINE_bool(btree_print_height, false, "");
DEFINE_bool(btree_print_tuples_count, false, "");
DEFINE_bool(btree_prefix_compression, true, "");
DEFINE_bool(btree_heads, true, "");
DEFINE_int64(btree_hints, 1, "");
DEFINE_bool(nc_reallocation, false, "");
DEFINE_bool(bulk_insert, false, "");
DEFINE_int64(trace_dt_id, -1, "");
DEFINE_int64(trace_trigger_probability, 100, "");
DEFINE_bool(pid_tracing, false, "");
DEFINE_bool(optimistic_parent_pointer, true, "");
DEFINE_bool(out_of_place, false, "");
DEFINE_uint64(replacement_chunk_size, 64, "");
DEFINE_bool(recycle_pages, true, "");
DEFINE_bool(wal, false, "");
DEFINE_bool(wal_rfa, true, "");
DEFINE_bool(wal_tuple_rfa, true, "");
DEFINE_uint64(wal_offset_gib, 10, "");
DEFINE_bool(wal_pwrite, false, "");
DEFINE_bool(wal_fsync, false, "");
DEFINE_int64(wal_variant, 0, "");
DEFINE_uint64(wal_log_writers, 1, "");
DEFINE_uint64(wal_buffer_size, 1024 * 1024 * 10, "");
DEFINE_uint64(si_refresh_rate, 0, "");
DEFINE_bool(todo, true, "");
DEFINE_bool(vi_delta, true, "");
DEFINE_bool(vi_utodo, true, "");
DEFINE_bool(vi_rtodo, true, "");
DEFINE_bool(vi_flookup, false, "");
DEFINE_bool(vi_fremove, false, "");
DEFINE_bool(vi_update_version_elision, false, "");
DEFINE_bool(vi_fupdate_chained, false, "");
DEFINE_bool(vi_fupdate_fat_tuple, false, "");
DEFINE_uint64(vi_pgc_batch_size, 2, "");
DEFINE_bool(vi_fat_tuple, false, "");
DEFINE_string(vi_fat_tuple_dts, "", "");
DEFINE_bool(vi_fat_tuple_decompose, true, "");
DEFINE_uint64(vi_fat_tuple_trigger, 0, "");
DEFINE_bool(vi_fat_tuple_alternative, false, "");
DEFINE_bool(vi_dangling_pointer, true, "");
DEFINE_bool(olap_mode, true, "");
DEFINE_bool(graveyard, true, "");
DEFINE_bool(pgc, true, "");
DEFINE_uint64(pgc_variant, 0, "");
DEFINE_double(garbage_in_page_pct, 15, "");
DEFINE_uint64(vi_max_chain_length, 1000, "");
DEFINE_uint64(todo_batch_size, 1024, "");
DEFINE_bool(history_tree_inserts, true, "");
